#!/usr/bin/env bash
# Update package
sudo apt update
# Install nginx
sudo apt install -y nginx
# Pass phrase to my html
sudo echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
# redirect
new_string="a location /redirect_me\n \t{ \n\t rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \n \t}"
sudo sed -i "/server_name _;/$new_string" /etc/nginx/sites-available/default
# Start nginx service
sudo service nginx start
### Create simple error 404 page.
echo "Ceci n'est pas une page" > /var/www/html/error_simple.html
### The redirection to Error page.
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/error_simple.html;/1" /etc/nginx/sites-available/default
### Start service nginx.
sudo service nginx restart
