#!/usr/bin/env bash
# This script redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html

# Redirect location
new_string="servername ;\n\n\tlocation /redirect_me {\n\t\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"

sudo sed -i "s/servername ;/$new_string/" /etc/nginx/sites-available/default

# Redirect 404
# Nginx server configuration to have a custom 404 page containing the string Ceci n'est pas une page
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

new_string2="servername ;\n\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/servername ;/$new_string2/" /etc/nginx/sites-available/default

# Redirect server
new_string3="a 404.\n\t\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s/a 404./$new_string3/" /etc/nginx/sites-available/default

service nginx restart
